import type { EmailSuggestion } from "@/modules/inbound-emails/lib/inbound-email-dto";

export const MOCK_EMAIL_SUGGESTIONS: EmailSuggestion[] = [
  {
    id: "mock-1",
    from: "sara.ali@example.com",
    subject: "Winter tire swap — Jan 8",
    receivedAt: "Dec 31, 3:52 PM",
    status: "matched",
    customerName: "Sarah Ali",
    appointmentDate: "Wed, Jan 8",
    email: "sara.ali@example.com",
    tireSet: "Winter set (4 tires)",
    vehicle: "2021 Toyota Camry",
    timeWindow: "09:30 – 13:45",
    windowOk: true,
    preview:
      "Hi,\nI'd like to book a winter tire change on Wednesday Jan 8 between 09:30 and 13:45. Vehicle is my 2021 Toyota Camry, plate XYZ-9821.\nThanks,\nSarah",
    shipmentRequestId: 2,
  },
  {
    id: "mock-2",
    from: "khalid.hassan@example.com",
    subject: "Urgent pickup tomorrow morning",
    receivedAt: "Dec 31, 2:10 PM",
    status: "window_too_short",
    customerName: "Khalid Hassan",
    appointmentDate: "Dec 31",
    email: "khalid.hassan@example.com",
    tireSet: "All‑season front pair",
    vehicle: "2019 Honda Accord",
    timeWindow: "10:05 – 10:20",
    windowOk: false,
    preview:
      "Can you squeeze me in tomorrow between 10:05 and 10:20 only? Front tires need rotation.\nBest,\nKhalid",
    shipmentRequestId: 3,
  },
  {
    id: "mock-3",
    from: "no.reply@carrier.net",
    subject: "(No subject)",
    receivedAt: "Dec 30, 6:41 PM",
    status: "parse_failed",
    customerName: "—",
    appointmentDate: "—",
    email: "—",
    tireSet: "—",
    vehicle: "—",
    timeWindow: "—",
    windowOk: false,
    preview: "Tracking #TX-9821731 departed facility — automated message.",
    shipmentRequestId: null,
  },
  {
    id: "mock-4",
    from: "mariam.saeed@example.com",
    subject: "Switch to summer rims",
    receivedAt: "Dec 30, 11:22 AM",
    status: "no_tires_stored",
    customerName: "Mariam Saeed",
    appointmentDate: "Fri, Jan 3",
    email: "mariam.saeed@example.com",
    tireSet: "Summer rims (stored off‑site)",
    vehicle: "2022 VW Golf",
    timeWindow: "Full day",
    windowOk: true,
    preview:
      "Hello team,\nPlease switch me back to summer rims this Friday. I don't have tires stored with you yet — I'll bring them in that morning.\nMariam",
    shipmentRequestId: null,
  },
];
